name: Create Environment

on:
  workflow_dispatch:

jobs:
  create-vpc:
    runs-on: ubuntu-latest

    steps:
      #Download only terraform archives to Environment
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          sparse-checkout: |
            terraform
          sparse-checkout-cone-mode: false

      #Configuration AWS Credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      #Configuration Terraform to commands
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2


      #Initialize, Definitive and Upload terraform for VPC
      - name: Terraform Init VPC
        working-directory: terraform/configurations/vpc
        run: terraform init
        
      - name: Terraform Apply VPC
        working-directory: terraform/configurations/vpc
        run: terraform apply -var-file="dev.tfvars"  -auto-approve

      - name: Upload Terraform State VPC to S3
        working-directory: terraform/configurations/vpc
        run: aws s3 cp terraform.tfstate s3://tfstate-viniciushemming-project-terraform-22082025/vpc/terraform.tfstate


      #Initialize, Definitive and Upload terraform for ECR
      - name: Terraform Init ECR
        working-directory: terraform/configurations/ecr
        run: terraform init

      - name: Terraform Apply ECR
        working-directory: terraform/configurations/ecr
        run: terraform apply -auto-approve

      - name: Upload Terraform State ECR to S3 VPC
        working-directory: terraform/configurations/ecr
        run: aws s3 cp terraform.tfstate s3://tfstate-viniciushemming-project-terraform-22082025/ecr/terraform.tfstate


      #Initialize, Definitive and Upload terraform for EKS
      - name: Terraform Init EKS
        working-directory: terraform/configurations/eks
        run: terraform init

      - name: Terraform Apply EKS
        working-directory: terraform/configurations/eks
        run: terraform apply -auto-approve

      - name: Upload Terraform State EKS to S3 VPC
        working-directory: terraform/configurations/eks
        run: aws s3 cp terraform.tfstate s3://tfstate-viniciushemming-project-terraform-22082025/eks/terraform.tfstate
