name: Create S3 Bucket

on:
  workflow_dispatch:

jobs:
  create-bucket:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          sparse-checkout: |
            terraform
          sparse-checkout-cone-mode: false

      #Configuration AWS Credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      #Configuration Terraform to commands
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

       #Create bucket S3
      - name: Terraform Init
        working-directory: terraform/configurations/s3
        run: terraform init

      - name: Terraform Apply
        working-directory: terraform/configurations/s3
        run: terraform apply -auto-approve


