name: Delete Environment

on:
  workflow_dispatch:

jobs:
  create-vpc:
    runs-on: ubuntu-latest

    steps:
      #Download only terraform archives to Environment
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          sparse-checkout: |
            terraform
          sparse-checkout-cone-mode: false

      #Configuration AWS Credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      #Configuration Terraform to commands
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      #Download Terraform State from S3
      - name: Download Terraform State from S3
        working-directory: terraform/configurations/vpc
        run: aws s3 cp s3://tfstate-viniciushemming-project-terraform-22082025/vpc/terraform.tfstate ./terraform.tfstate

      #Initialize terraform for VPC
      - name: Terraform Init
        working-directory: terraform/configurations/vpc
        run: terraform init

      #Definitive Creation of VPC
      - name: Terraform Destroy
        working-directory: terraform/configurations/vpc
        run: terraform destroy -var-file="dev.tfvars" -auto-approve
