name: Delete Environment

on:
  workflow_dispatch:

jobs:
  delete-environment:
    runs-on: ubuntu-latest

    steps:
      #Download only terraform archives to Environment
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          sparse-checkout: |
            terraform
          sparse-checkout-cone-mode: false

      #Configuration AWS Credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      #Configuration Terraform to commands
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2


      #Download all packages from S3
      - name: Download Terraform State EKS from S3
        working-directory: terraform/configurations/eks
        run: aws s3 cp s3://tfstate-viniciushemming-project-terraform-22082025/eks/terraform.tfstate ./terraform.tfstate

      - name: Download Terraform State ECR from S3
        working-directory: terraform/configurations/ecr
        run: aws s3 cp s3://tfstate-viniciushemming-project-terraform-22082025/ecr/terraform.tfstate ./terraform.tfstate

      - name: Download Terraform State from S3
        working-directory: terraform/configurations/vpc
        run: aws s3 cp s3://tfstate-viniciushemming-project-terraform-22082025/vpc/terraform.tfstate ./terraform.tfstate

        
   
      #Initialize and Destroy Terraform EKS
      - name: Terraform Init EKS
        working-directory: terraform/configurations/eks
        run: terraform init

      - name: Terraform Destroy EKS
        working-directory: terraform/configurations/eks
        run: terraform destroy -auto-approve

      - name: Delete Load Balancers from EKS if exist
        run: |
          # Instalar jq (se necessário)
          sudo apt-get update && sudo apt-get install -y jq
          LB_ARNS=$(aws elbv2 describe-load-balancers --query "LoadBalancers[].LoadBalancerArn" --output text)
          for lb in $LB_ARNS; do
            TAGS=$(aws elbv2 describe-tags --resource-arns $lb --output json)
            CLUSTER_TAG=$(echo $TAGS | jq -r '.TagDescriptions[0].Tags[] | select(.Key=="kubernetes.io/cluster/eksprojectviniciushemming") | .Value')
            SERVICE_TAG=$(echo $TAGS | jq -r '.TagDescriptions[0].Tags[] | select(.Key=="kubernetes.io/service-name") | .Value')
            if [[ "$CLUSTER_TAG" == "owned" && "$SERVICE_TAG" == "default/python-sample-service" ]]; then
              echo "Deletando Load Balancer $lb..."
              aws elbv2 delete-load-balancer --load-balancer-arn $lb
            fi
          done
        env:
          AWS_DEFAULT_REGION: us-east-1
          AWS_REGION: us-east-1
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          

      #Initialize and Destroy Terraform ECR
      - name: Terraform Init ECR
        working-directory: terraform/configurations/ecr
        run: terraform init
      
      - name: Terraform Destroy ECR
        working-directory: terraform/configurations/ecr
        run: terraform destroy -auto-approve


      #Initialize and Destroy Terraform VPC
      - name: Terraform Init VPC
        working-directory: terraform/configurations/vpc
        run: terraform init

      - name: Terraform Destroy VPC
        working-directory: terraform/configurations/vpc
        run: terraform destroy -var-file="dev.tfvars" -auto-approve
